version: '3.8'

services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: vprocontainers/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
      - MYSQL_DATABASE=accounts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  vprocache01:
    image: memcached
    container_name: vprocache01
    ports:
      - "11211:11211"
    restart: unless-stopped

  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped

  vproapp:
    build: 
      context: ./Docker-files/app
    image: vprocontainers/vprofileapp
    container_name: vproapp
    ports:
      - "8081:8080"
    depends_on:
      vprodb:
        condition: service_healthy
      vprocache01:
        condition: service_started
      vpromq01:
        condition: service_started
    environment:
      - DB_HOST=vprodb
      - DB_PORT=3306
      - DB_NAME=accounts
      - DB_USER=root
      - DB_PASS=vprodbpass
    restart: unless-stopped

  vproweb:
    build: 
      context: ./Docker-files/web
    image: vprocontainers/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
    depends_on:
      - vproapp
    restart: unless-stopped

volumes:
  vprodbdata: {}
  vproappdata: {}
