apiVersion: v1
kind: ConfigMap
metadata:
  name: load-test-script
  namespace: vprofile
data:
  load-test.sh: |
    #!/bin/bash
    echo "Starting load test..."
    
    # Get service URL
    SERVICE_URL="http://vproapp-service:8080"
    
    # Run concurrent requests
    for i in {1..10}; do
      (
        while true; do
          curl -s $SERVICE_URL > /dev/null
          sleep 0.1
        done
      ) &
    done
    
    echo "Load test running with 10 concurrent threads"
    echo "Monitor scaling with: kubectl get hpa -n vprofile -w"
    wait
---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
  namespace: vprofile
spec:
  template:
    spec:
      containers:
      - name: load-test
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args: ["/scripts/load-test.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: load-test-script
          defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 1