apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  namespace: vprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: vprocontainers/vprofiledb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "vprodbpass"
        - name: MYSQL_DATABASE
          value: "accounts"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vprodb
  namespace: vprofile
spec:
  selector:
    app: vprodb
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: vprofile
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi