apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproweb
  namespace: vprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vproweb
  template:
    metadata:
      labels:
        app: vproweb
    spec:
      containers:
      - name: vproweb
        image: vprocontainers/vprofileweb:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vproweb-service
  namespace: vprofile
spec:
  selector:
    app: vproweb
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer